image: node:14

cache:
  paths:
    - node_modules/

stages:
  - check
  - build
  - test
  - publish

# stage: check ----------------------

eslint:
  stage: check
  script:
    - npm install
    - npm run lint

# stage: build ----------------------

build docker image:
  image: docker:latest
  stage: build
  dependencies:
    - "eslint" # For cache
  script:
    - docker image build -t $DOCKER_REGISTRY/deepl/deepl-mock .
    - docker image build -t deepl/deepl-mock .

# stage: test ----------------------

dummy test:
  stage: test
  script:
    - export DEEPL_MOCK_SERVER_PORT=3000
    - export DEEPL_MOCK_PROXY_SERVER_PORT=3001
    - node index.js &
    - sleep 1
    - node test/smoke_test.js

# stage: publish ----------------------

publish latest to internal repository:
  image: docker:latest
  stage: publish
  dependencies:
    - "build docker image"
  script:
    - docker image push $DOCKER_REGISTRY/deepl/deepl-mock
